WIP: Follow button
H-PixelDroid/PixelDroid pull request #109
Opened 2020-04-17 15:29 UTC by mjaillot

2020-04-17 20:14 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes

2020-04-17 20:14 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/objects/Account.kt
> +                    if (response.body()!![0].following) {
Faudrait vérifier que y a bien une relation dans la réponse, si non on peut juste jamais afficher le bouton. (pas rendre VISIBLE)

2020-04-17 20:14 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/objects/Account.kt
> +                            setOnClickUnfollow(view, api, context, credential)
comme ces fonctions sont jamais appelé autrement, on pourrait refactor le view.followButton.setOnClickListener dans la fonction

2020-04-19 11:55 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/fragments/ProfileFragment.kt
> -            followButton.visibility = View.GONE
Enlever ça fait que le bouton est INVISIBLE au lieu de GONE, du coup je sais pas si il prend pas de la place dans le layout

2020-04-19 11:56 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 submitted a review, later dismissed

2020-04-19 12:01 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes

2020-04-19 12:01 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/objects/Account.kt
> +                    if(response.body()!![0].following) {
Vérifier qu'il y a bien une relation dans la réponse, sinon on devrait rien faire (pas d'affichage de bouton)

2020-04-24 07:00 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/fragments/feeds/FollowsFragment.kt
> +                    max_id = key, limit = requestedLoadSize)
Pas sûr que c'est max_id ici, je pense que since_id est ce qu'il faut. De toute façon l'API respecte pas cet argument pour le moment, donc c'est dûr d'être sûr.

2020-04-24 10:09 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 approved these changes

2020-04-24 10:09 UTC, dobios approved these changes

2020-04-24 10:10 UTC, merged