Added a dark mode
H-PixelDroid/PixelDroid pull request #151
Opened 2020-05-07 13:57 UTC by Dobios

2020-05-08 13:53 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented
Serait bien d'enlever les settings inutiles et leurs strings associés tant qu'on y est

2020-05-08 15:28 UTC, ulysse42 commented on app/src/main/java/com/h/pixeldroid/utils/ThemeUtils.kt
> +            }
tu peux réunir le themes[0] et le else, ça te fera un test de moins à écrire

2020-05-08 15:43 UTC, ulysse42 submitted a review, later dismissed
update new stuff

2020-05-14 19:06 UTC, ulysse42 commented on app/src/main/res/layout/activity_login.xml
> +                    android:layout_marginTop="36dp"
enlève ce marginTop stp

2020-05-14 19:08 UTC, ulysse42 approved these changes

2020-05-14 19:15 UTC, ulysse42 requested changes

2020-05-14 19:15 UTC, ulysse42 commented on app/src/androidTest/java/com/h/pixeldroid/DrawerMenuTest.kt
> +        onView(withText("Default")).perform(click())
il faut mettre le string complet avec withText(), et tu peux utiliser les strings depuis R.string plutot que hardcoder, comme on a dit avant

2020-05-14 19:51 UTC, Dobios commented on app/src/androidTest/java/com/h/pixeldroid/DrawerMenuTest.kt
> +        onView(withText("Default")).perform(click())
oh right thanks

2020-05-14 19:52 UTC, Dobios commented on app/src/main/res/layout/activity_login.xml
> +                    android:layout_marginTop="36dp"
done

2020-05-14 19:54 UTC, ulysse42 approved these changes

2020-05-15 07:22 UTC, SoupeDeKiwis approved these changes

2020-05-15 07:23 UTC, merged