WIP: database
H-PixelDroid/PixelDroid pull request #156
Opened 2020-05-08 09:10 UTC by ulysse42

2020-05-13 18:44 UTC, dobios approved these changes

2020-05-14 14:02 UTC, mjaillot requested changes

2020-05-14 14:02 UTC, mjaillot commented on app/src/main/java/com/h/pixeldroid/objects/Account.kt
> +    val display_name: String = "",
Now that display_name is not nullable, you should just change `getUsername()` in Status.kt (line 125).

2020-05-14 18:07 UTC, mjaillot approved these changes

2020-05-14 18:14 UTC, merged