WIP: Translatable text
H-PixelDroid/PixelDroid pull request #164
Opened 2020-05-15 07:58 UTC by mjaillot

2020-05-15 14:05 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 approved these changes

2020-05-17 08:46 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes
Should add a comment on the line before every string to the strings XML file, like so:     

> \<!-- This string is for X --\>

 for example. This way the translators have some context when translating.

2020-05-19 05:46 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/ProfileActivity.kt
> +            account!!.statuses_count.toString() + applicationContext.getString(R.string.nb_posts)
Should use templates instead of concatenating strings (see notifications)

2020-05-21 12:30 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/res/values/strings.xml
> +    <!-- Notifications -->
A comment is only visible for the string right under it in weblate. However, I don't think comments are necessary for all strings, a lot of strings are easy to understand what they are for.

2020-05-21 12:41 UTC, dobios approved these changes

2020-05-21 13:21 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 approved these changes

2020-05-21 13:22 UTC, merged