WIP: Notifications badge
H-PixelDroid/PixelDroid pull request #205
Opened 2020-05-21 20:36 UTC by Dobios

2020-05-21 21:36 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes
Creating a new table won't play nice with multi-user. I suggest just adding an attribute to the user db.

2020-05-22 07:24 UTC, Dobios commented
> Creating a new table won't play nice with multi-user. I suggest just adding an attribute to the user d

Good point, will change

2020-05-22 11:16 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes

2020-05-22 11:16 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/MainActivity.kt
> +                                        val resultingId = (response.body() as List<Notification>)[0].id.toInt()
This list can be empty. This will then crash

2020-05-22 11:16 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/MainActivity.kt
> +                                    Toast.makeText(applicationContext, resources.getString(R.string.feed_failed), Toast.LENGTH_SHORT).show()
faire attention à quels strings sont affichés, je pense pas que c'est feed_failed qu'il faut ici

2020-05-22 11:16 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/MainActivity.kt
> +            NotificationUtils.updateLatestIdDBEntry(
C'est pas déjà fait dans le getUpdatedAccount ça?

2020-05-22 11:16 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented on app/src/main/java/com/h/pixeldroid/MainActivity.kt
> +                    } else {
Heu c'est ça ton bug que ça le met à jour pour tous les tabs, non?

2020-06-26 09:02 UTC, closed without merging