Feature/17
H-PixelDroid/PixelDroid pull request #24
Opened 2020-03-05 08:09 UTC by ulysse42

2020-03-05 20:23 UTC, Sanimys approved these changes

2020-03-05 22:41 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 requested changes
Il faut faire un test (#27 a des tests UI si tu veux de l'inspiration)
Il faudrait que ce soit des tabs, cad il faut pouvoir swipe de l'un à l'autre
Je sais pas pk le bouton home re-lance la même activité?

2020-03-06 00:56 UTC, ulysse42 commented
> Il faut faire un test (#27 a des tests UI si tu veux de l'inspiration)
> Il faudrait que ce soit des tabs, cad il faut pouvoir swipe de l'un à l'autre
Comment on fait ça ? Il faut tout faire dans la même activity du coup ?
> Je sais pas pk le bouton home re-lance la même activité?
Car en cliquant sur le bouton home ça doit recharger la homepage (MainActivity)

2020-03-06 07:20 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented
> Car en cliquant sur le bouton home ça doit recharger la homepage (MainActivity)

Peut-être mais pas en re-lancant l'activité, plutôt en rechargant la liste de posts. Je pense qu'il vaut mieux rien faire en attendant qu'on a cette liste

2020-03-07 21:50 UTC, closed without merging