User profile #79
H-PixelDroid/PixelDroid pull request #90
Opened 2020-04-03 09:36 UTC by mjaillot

Links to profile activity when needed (click on username or picture)
Refactored layout and show posts.
Issue #79

2020-04-03 09:44 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 submitted a review, later dismissed

2020-04-03 09:46 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 commented
Faudrait augmenter le coverage, mais une fois que c'est fait, lgtm

2020-04-05 12:59 UTC, ulysse42 requested changes
enlève le chunk de code commenté pour master stp

2020-04-05 12:59 UTC, ulysse42 commented on app/src/androidTest/java/com/h/pixeldroid/ProfileTest.kt
> +}*/
this

2020-04-06 10:23 UTC, ulysse42 submitted a review, later dismissed

2020-04-09 19:28 UTC, Wv5twkFEKh54vo4tta9yu7dHa3 approved these changes

2020-04-09 20:13 UTC, ulysse42 approved these changes

2020-04-09 20:37 UTC, merged